### ISSUE TITLE
Windows functionality

### ISSUE THREAD

**Issue by iandoesallthethings** [partials-dev/pulse#10]
# Windows 10

Crashed during clean step of build process. I changed the clean step in package.json to:
``"clean": "del .\\js\\dist || true",``

It builds and launches successfully, but the window is too small and the gif seems to stutter.

![pulsewin](https://cloud.githubusercontent.com/assets/15148313/20807384/ac94188a-b7cc-11e6-8b42-789811a0b042.PNG)

**Comment by luca-aurelia** [comment]
I think 2d877f634fb6ffc68b04e895a806d79342917f2a will make the regular `npm run start` command work on Windows. @denkyuu, could you pull and confirm?

**Comment by iandoesallthethings** [comment]
It WORKS! What did you change?

Edit; nevermind, it's only loading the spirit animal now.

**Comment by luca-aurelia** [comment]
Hmm, okay. Let's take a look this evening. I'm also in the middle of a bunch of messy work, so it might just be the result of a sloppy commit. In the meantime, could you create a separate issue for the  Ubuntu error you found?

**Comment by iandoesallthethings** [comment]
### Summary of latest state:
Now builds successfully, but loads without controls.

```Loading http://67.media.tumblr.com/4a2ecf3258e23674bc4b253fd74bfa81/tumblr_msz5x3ACVh1qcoae6o1_400.gif

C:\Users\Ian\dev\partials\pulse\js\src\renderer.js:10 
Uncaught SyntaxError: Unexpected token import

EXPLODING
http://67.media.tumblr.com/4a2ecf3258e23674bc4b253fd74bfa81/tumblr_msz5x3ACVh1qcoae6o1_400.gif

Received 50 frames of gif 
http://67.media.tumblr.com/4a2ecf3258e23674bc4b253fd74bfa81/tumblr_msz5x3ACVh1qcoae6o1_400.gif

```
![pulsewin2](https://cloud.githubusercontent.com/assets/15148313/20808344/355d6b0a-b7d0-11e6-88a9-65e7a0710a1a.PNG)
